In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.10.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix 
another_matrix = tf.constant([[10.,8.], [3.,2.], [8.,9.]], dtype=tf.float16)
changeable_tensor = tf.Variable([7,9]) 
changeable_tensor[0].assign(8)
another_matrix, changeable_tensor

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  8.],
        [ 3.,  2.],
        [ 8.,  9.]], dtype=float16)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 9])>)

In [15]:
# Create Random Tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [16]:
# random shuffle tensor
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>